source "https://rubygems.org"

gem 'startback-engine', path: '..'
gem 'startback-web', path: '..'

group :test do
  gem 'rake'
  gem 'rspec', ['>= 3.6', '< 4.0']
  gem 'rspec_junit_formatter', [">= 0.4.1", "< 0.5"]
  gem 'webspicy', '~> 0.23.0', '< 0.24'
end
