source "https://rubygems.org"

gem 'startback-engine', path: '..'
gem 'startback-web', path: '..'
gem 'startback-websocket', path: '../contrib/startback-websocket'

group :test do
  gem 'rake'
  gem 'rspec', ['>= 3.6', '< 4.0']
  gem 'rspec_junit_formatter', [">= 0.4.1", "< 0.5"]
  gem 'webspicy', '~> 0.20.0', '>= 0.20.5'
end
