FROM startback:base

COPY . /tmp/startback
RUN cd /tmp/startback && \
    mkdir -p /tmp/startback/pkg && \
    gem build -o pkg/startback-api.gem startback-api.gemspec && \
    gem install pkg/startback-api.gem && \
    rm -rf /tmp/startback

USER app

CMD bundle exec puma -p 3000
