FROM enspirit/startback-base-2.7

COPY . /tmp/startback
RUN cd /tmp/startback && \
    gem build -o pkg/startback-engine.gem startback-engine.gemspec && \
    gem install pkg/startback-engine.gem && \
    rm -rf /tmp/startback

USER app
CMD bundle exec ruby engine.rb
