FROM enspirit/startback:base

COPY . /tmp/startback
RUN cd /tmp/startback && \
    mkdir -p /tmp/startback/pkg && \
    gem build -o pkg/startback-engine.gem startback-engine.gemspec && \
    gem install pkg/startback-engine.gem && \
    rm -rf /tmp/startback

USER app

CMD bundle exec puma -t 1:1 -w 1 -p 3000 config.engine.ru
