FROM startback:base

RUN apk add --update nodejs

COPY . /tmp/startback
RUN cd /tmp/startback && \
    mkdir -p /tmp/startback/pkg && \
    gem build -o pkg/startback-web.gem startback-web.gemspec && \
    gem install pkg/startback-web.gem && \
    rm -rf /tmp/startback

USER app

CMD bundle exec puma -t 1:5 -w 1 -p 3000
