name: Release Images

on:
  push:
    branches:
    - master
    tags:
      - "*"

jobs:
  Tests:
    uses: enspirit/startback/.github/workflows/tests.yml@master

  Release:
    needs: Tests
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Get tag if exist
        run: echo "VERSION=$(git describe --contains || true)" >> $GITHUB_ENV

      - name: Building images
        id: build-images
        run: make images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pushing images
        id: push-images
        run: make images.push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
