name: Running tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.4.1']
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Bundling
        run: make bundle

      - name: Run tests
        run: make tests
